[tool.poetry]
name = "giradischi"
version = "1.2.0"
description = "GUI MIDI player supporting multiple backends"
authors = ["Sebastiano Barezzi <seba@sebaubuntu.dev>"]
license = "LGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/python-midi/giradischi"

[tool.poetry.scripts]
giradischi = 'giradischi.main:main'

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
libmidi = "^1.1.0"
libmidi-io = "^1.1.0"
PySide6 = "^6.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
